FROM node:22-bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    lsof \
    && curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard

ENV NODE_ENV=production
